In [25]:
import numpy as np

In [26]:
def f(x):
    return 1.0 / (1 + np.exp(-x))

In [27]:
X = np.array([[0], [1]])

W1 = np.array([[1, 0.5], [-1, 2]])
O1= np.array([[1], [1]])

W2 = np.array([[1.5, -1]])
O2= np.array([[1]])
    

In [28]:
def MatrixVector(W1, X):
    n, m = np.shape(W1)
    b = [0] * n
    for i in range(0, n): # перебираем номера строк матрицы
        s = 0
        for j in range(0, m):
            s += W1[i, j] * X[j]
        b[i] = s
    return b


U1 = MatrixVector(W1, X) + O1
U1

array([[1.5],
       [3. ]])

In [29]:
Y1 = f(U1)
Y1

array([[0.81757448],
       [0.95257413]])

In [30]:
U2 = MatrixVector(W2, Y1) + O2
U2

array([[1.27378759]])

In [31]:
Y2 = f(U2)
Y2

array([[0.78139043]])